# Generated by Django 4.0 on 2021-12-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, unique=True)),
                ('user_application_id', models.CharField(max_length=12, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_picture', models.ImageField(upload_to='userprofile/')),
                ('first_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('auth_token', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_user_table',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid_verification', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.appusertable')),
            ],
            options={
                'db_table': 'email_verify_table',
            },
        ),
    ]
