version: "3.8"

services:
  db:
    image: postgres
    container_name: "bank_app-db"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "7680:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "echo","Hello" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    container_name: "bank_app"
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80 --insecure"
    volumes:
      - .:/BankApp
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  postgres_data:
