version: '3.7'

services:
  web:
    build: .
    container_name: infra_django_app
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: infra_django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello

  nginx:
    build: ./nginx
    container_name: infra_django_nginx
    volumes:
      - staticfiles:/app/static/
    ports:
      - '8008:80'
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles: