version: '3.8'

services:
  web:
    container_name: "exam_app"
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn MainRoot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: "app_db"
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - "7600:5432"
  nginx:
    container_name: "nginx_app"
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: