# Generated by Django 4.0 on 2021-12-28 05:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyEmailTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid_verification', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'verify_email_table',
            },
        ),
        migrations.CreateModel(
            name='UserTokenTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_token', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'user_token_table',
            },
        ),
        migrations.CreateModel(
            name='UserProfileTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_profile_image', models.ImageField(upload_to='userprofile/')),
                ('user_account_number', models.BigIntegerField(unique=True)),
                ('user_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'user_profile_table',
            },
        ),
        migrations.CreateModel(
            name='ResetPasswordTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid_verification', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'reset_password_table',
            },
        ),
    ]
